{
 "title": "Switch-254",
 "tags": [ "Switch" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "Grupo", "query": "*" },
   { "name": "Host", "query": "$Grupo.*" }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "Switch" },
     "host": { "filter": "Switch_6F_Core" },
     "item": { "filter": "Cisco IOS: ICMP ping" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Tempo Ligado",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Status Administrativo das Interface de Rede"
     },
     "evaltype": "0",
     "group": { "filter": "Switch" },
     "host": { "filter": "Switch_6F_Core" },
     "item": { "filter": "Cisco IOS: Uptime (network)" },
     "itemTag": { "filter": "component: system" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  { "title": "IP", "type": "text", "gridPos": { "h": 2, "w": 4, "x": 6, "y": 0 }, "options": { "content": "**192.168.0.254**" } },
  {
   "title": "Pacotes Loss",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Status Administrativo das Interface de Rede"
     },
     "evaltype": "0",
     "group": { "filter": "Switch" },
     "host": { "filter": "Switch_6F_Core" },
     "item": { "filter": "Cisco IOS: ICMP loss" },
     "itemTag": { "filter": "component: network" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Memory Processador",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "Switch" },
     "host": { "filter": "Switch_6F_Core" },
     "item": { "filter": "I/O: Used memory" },
     "itemTag": { "filter": "component: memory" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "Switch" },
     "host": { "filter": "Switch_6F_Core" },
     "item": { "filter": "Processor: Used memory" },
     "itemTag": { "filter": "component: memory" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "Switch" },
     "host": { "filter": "Switch_6F_Core" },
     "item": { "filter": "#19: CPU utilization" },
     "itemTag": { "filter": "component: cpu" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "Status FAN",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Status Administrativo das Interface de Rede"
     },
     "evaltype": "0",
     "group": { "filter": "Switch" },
     "host": { "filter": "Switch_6F_Core" },
     "item": {
      "filter": "Switch 1 - FAN - T1 1, Normal: Fan status"
     },
     "itemTag": { "filter": "component: fan" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Memory I/O",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 6, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "Switch" },
     "host": { "filter": "Switch_6F_Core" },
     "item": { "filter": "reserve Processor: Free memory" },
     "itemTag": { "filter": "component: memory" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "Memory Processador",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 10, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "Switch" },
     "host": { "filter": "Switch_6F_Core" },
     "item": { "filter": "Processor: Memory utilization" },
     "itemTag": { "filter": "component: memory" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  { "title": "Status das interfaces", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Gi0/1",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Status Administrativo das Interface de Rede"
     },
     "evaltype": "0",
     "group": { "filter": "Switch" },
     "host": { "filter": "Switch_6F_Core" },
     "item": {
      "filter": "Interface Gi1/0/1(): Operational status"
     },
     "itemTag": { "filter": "interface: Gi1/0/1" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Gi0/2",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Status Administrativo das Interface de Rede"
     },
     "evaltype": "0",
     "group": { "filter": "Switch" },
     "host": { "filter": "Switch_6F_Core" },
     "item": {
      "filter": "Interface Gi1/0/5(old db-->MF2K): Operational status"
     },
     "itemTag": { "filter": "description: old db-->MF2K" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Gi0/3",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Status Administrativo das Interface de Rede"
     },
     "evaltype": "0",
     "group": { "filter": "Switch" },
     "host": { "filter": "Switch_6F_Core" },
     "item": {
      "filter": "Interface Gi1/0/3(): Operational status"
     },
     "itemTag": { "filter": "interface: Gi1/0/3" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Gi0/4",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Status Administrativo das Interface de Rede"
     },
     "evaltype": "0",
     "group": { "filter": "Switch" },
     "host": { "filter": "Switch_6F_Core" },
     "item": {
      "filter": "Interface Gi1/0/4(old nas): Operational status"
     },
     "itemTag": { "filter": "interface: Gi1/0/4" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Gi0/5",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Status Administrativo das Interface de Rede"
     },
     "evaltype": "0",
     "group": { "filter": "Switch" },
     "host": { "filter": "Switch_6F_Core" },
     "item": {
      "filter": "Interface Gi1/0/5(old db-->MF2K): Operational status"
     },
     "itemTag": { "filter": "interface: Gi1/0/5" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Gi0/6",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Status Administrativo das Interface de Rede"
     },
     "evaltype": "0",
     "group": { "filter": "Switch" },
     "host": { "filter": "Switch_6F_Core" },
     "item": {
      "filter": "Interface Gi1/0/6(ERP-AP01): Operational status"
     },
     "itemTag": { "filter": "interface: Gi1/0/6" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Gi0/7",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Status Administrativo das Interface de Rede"
     },
     "evaltype": "0",
     "group": { "filter": "Switch" },
     "host": { "filter": "Switch_6F_Core" },
     "item": {
      "filter": "Interface Gi1/0/7(): Operational status"
     },
     "itemTag": { "filter": "interface: Gi1/0/7" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Gi0/8",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Status Administrativo das Interface de Rede"
     },
     "evaltype": "0",
     "group": { "filter": "Switch" },
     "host": { "filter": "Switch_6F_Core" },
     "item": {
      "filter": "Interface Gi1/0/8(): Operational status"
     },
     "itemTag": { "filter": "interface: Gi1/0/8" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Gi0/9",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Status Administrativo das Interface de Rede"
     },
     "evaltype": "0",
     "group": { "filter": "Switch" },
     "host": { "filter": "Switch_6F_Core" },
     "item": {
      "filter": "Interface Gi1/0/9(): Operational status"
     },
     "itemTag": { "filter": "interface: Gi1/0/9" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Gi0/10",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Status Administrativo das Interface de Rede"
     },
     "evaltype": "0",
     "group": { "filter": "Switch" },
     "host": { "filter": "Switch_6F_Core" },
     "item": {
      "filter": "Interface Gi1/0/10(): Operational status"
     },
     "itemTag": { "filter": "interface: Gi1/0/10" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Gi0/11",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Status Administrativo das Interface de Rede"
     },
     "evaltype": "0",
     "group": { "filter": "Switch" },
     "host": { "filter": "Switch_6F_Core" },
     "item": {
      "filter": "Interface Gi1/0/11(): Operational status"
     },
     "itemTag": { "filter": "interface: Gi1/0/11" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Gi0/12",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Status Administrativo das Interface de Rede"
     },
     "evaltype": "0",
     "group": { "filter": "Switch" },
     "host": { "filter": "Switch_6F_Core" },
     "item": {
      "filter": "Interface Gi1/0/12(): Operational status"
     },
     "itemTag": { "filter": "interface: Gi1/0/12" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Gi0/13",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Status Administrativo das Interface de Rede"
     },
     "evaltype": "0",
     "group": { "filter": "Switch" },
     "host": { "filter": "Switch_6F_Core" },
     "item": {
      "filter": "Interface Gi1/0/13(): Operational status"
     },
     "itemTag": { "filter": "interface: Gi1/0/13" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Gi0/14",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Status Administrativo das Interface de Rede"
     },
     "evaltype": "0",
     "group": { "filter": "Switch" },
     "host": { "filter": "Switch_6F_Core" },
     "item": {
      "filter": "Interface Gi1/0/14(): Operational status"
     },
     "itemTag": { "filter": "interface: Gi1/0/14" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Gi0/15",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Status Administrativo das Interface de Rede"
     },
     "evaltype": "0",
     "group": { "filter": "Switch" },
     "host": { "filter": "Switch_6F_Core" },
     "item": {
      "filter": "Interface Gi1/0/15(): Operational status"
     },
     "itemTag": { "filter": "component: network" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Gi0/16",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Status Administrativo das Interface de Rede"
     },
     "evaltype": "0",
     "group": { "filter": "Switch" },
     "host": { "filter": "Switch_6F_Core" },
     "item": {
      "filter": "Interface Gi1/0/16(): Operational status"
     },
     "itemTag": { "filter": "component: network" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Gi0/17",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Status Administrativo das Interface de Rede"
     },
     "evaltype": "0",
     "group": { "filter": "Switch" },
     "host": { "filter": "Switch_6F_Core" },
     "item": {
      "filter": "Interface Gi1/0/17(): Operational status"
     },
     "itemTag": { "filter": "component: network" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Gi0/18",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Status Administrativo das Interface de Rede"
     },
     "evaltype": "0",
     "group": { "filter": "Switch" },
     "host": { "filter": "Switch_6F_Core" },
     "item": {
      "filter": "Interface Gi1/0/18(): Operational status"
     },
     "itemTag": { "filter": "interface: Gi1/0/18" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Gi0/19",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Status Administrativo das Interface de Rede"
     },
     "evaltype": "0",
     "group": { "filter": "Switch" },
     "host": { "filter": "Switch_6F_Core" },
     "item": {
      "filter": "Interface Gi1/0/19(): Operational status"
     },
     "itemTag": { "filter": "interface: Gi1/0/19" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Gi0/20",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Status Administrativo das Interface de Rede"
     },
     "evaltype": "0",
     "group": { "filter": "Switch" },
     "host": { "filter": "Switch_6F_Core" },
     "item": {
      "filter": "Interface Gi1/0/20(): Operational status"
     },
     "itemTag": { "filter": "interface: Gi1/0/20" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Gi0/21",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Status Administrativo das Interface de Rede"
     },
     "evaltype": "0",
     "group": { "filter": "Switch" },
     "host": { "filter": "Switch_6F_Core" },
     "item": {
      "filter": "Interface Gi1/0/21(): Operational status"
     },
     "itemTag": { "filter": "interface: Gi1/0/21" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Gi0/22",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Status Administrativo das Interface de Rede"
     },
     "evaltype": "0",
     "group": { "filter": "Switch" },
     "host": { "filter": "Switch_6F_Core" },
     "item": {
      "filter": "Interface Gi1/0/22(): Operational status"
     },
     "itemTag": { "filter": "interface: Gi1/0/22" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Gi0/23",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Status Administrativo das Interface de Rede"
     },
     "evaltype": "0",
     "group": { "filter": "Switch" },
     "host": { "filter": "Switch_6F_Core" },
     "item": {
      "filter": "Interface Gi1/0/23(): Operational status"
     },
     "itemTag": { "filter": "interface: Gi1/0/23" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Gi0/24",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Status Administrativo das Interface de Rede"
     },
     "evaltype": "0",
     "group": { "filter": "Switch" },
     "host": { "filter": "Switch_6F_Core" },
     "item": {
      "filter": "Interface Gi1/0/24(): Operational status"
     },
     "itemTag": { "filter": "interface: Gi1/0/24" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  }
 ]
}