{
 "title": "UPS-科風",
 "tags": [ "UPS" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "電池容量",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "Templates/Power" },
     "host": { "filter": "UPS-Web7" },
     "item": { "filter": "APC UPS: Battery capacity" },
     "itemTag": { "filter": "component: power" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "剩餘時間",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "Templates/Power" },
     "host": { "filter": "UPS-Web7" },
     "item": {
      "filter": "APC UPS: Battery runtime remaining"
     },
     "itemTag": { "filter": "component: power" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "溫度",
   "type": "stat",
   "gridPos": { "h": 10, "w": 5, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "Templates/Power" },
     "host": { "filter": "UPS-Web7" },
     "item": { "filter": "APC UPS: Battery temperature" },
     "itemTag": { "filter": "component: temperature" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "輸出電壓",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "Templates/Power" },
     "host": { "filter": "UPS-Web7" },
     "item": { "filter": "APC UPS: Output voltage" },
     "itemTag": { "filter": "component: power" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "電池負載",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "Templates/Power" },
     "host": { "filter": "UPS-Web7" },
     "item": { "filter": "APC UPS: Output load" },
     "itemTag": { "filter": "component: power" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "電池電壓",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 11, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "Templates/Power" },
     "host": { "filter": "UPS-Web7" },
     "item": { "filter": "APC UPS: Battery voltage" },
     "itemTag": { "filter": "component: power" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  }
 ]
}